# Site settings
title: Ludvig Larsendahl
description: > # this means to ignore newlines until "baseurl:"
  Self-taught developer with a passion for computers.
  Programming, video-, audio-, and photo editing,
  are only some of the things I've done.
baseurl: ""
url: "https://ludvig.larsendahl.se"

# Build settings
markdown: kramdown

