# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UK-Sidan 
email: ludvig@larsendahl.se
description: > # this means to ignore newlines until "baseurl:"
  V채ster책s SOK UK-sidan
keywords: "UK, VSOK, V채ster책s SOK, UK-sidan"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vasterassok-uk.github.io/uk-sidan/" # the base hostname & protocol for your site
twitter_username: ghostopsz
github_username:  ghostops

# Build settings
markdown: kramdown

